### ISSUE TITLE
Error using IDENTITY_H as pdf.encoding

### ISSUE THREAD

**Issue by bartoleo** [gpc/export#12]
I'm trying to export using IDENTITY_H as pdf.encoding (text contains slovenian text)

I get this exception:
Error during export
| Error ExceptionConverter: 
| Error java.io.UnsupportedEncodingException: Identity-H
| Error 	at java.lang.StringCoding.encode(StringCoding.java:341)
| Error 	at java.lang.String.getBytes(String.java:916)
| Error 	at com.lowagie.text.pdf.PdfEncodings.convertToBytes(Unknown Source)
| Error 	at com.lowagie.text.pdf.Type1Font.<init>(Unknown Source)
| Error 	at com.lowagie.text.pdf.BaseFont.createFont(Unknown Source)
| Error 	at com.lowagie.text.pdf.BaseFont.createFont(Unknown Source)
| Error 	at com.lowagie.text.FontFactoryImp.getFont(Unknown Source)
| Error 	at com.lowagie.text.FontFactoryImp.getFont(Unknown Source)
| Error 	at com.lowagie.text.FontFactory.getFont(Unknown Source)
| Error 	at com.lowagie.text.FontFactory.getFont(Unknown Source)
| Error 	at sun.reflect.GeneratedMethodAccessor1534.invoke(Unknown Source)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
| Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
| Error 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:133)
| Error 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
| Error 	at de.andreasschmitt.export.exporter.DefaultPDFExporter.createFont(DefaultPDFExporter.groovy:256)
| Error 	at sun.reflect.GeneratedMethodAccessor1533.invoke(Unknown Source)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1459)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
| Error 	at de.andreasschmitt.export.exporter.DefaultPDFExporter.exportData(DefaultPDFExporter.groovy:54)
| Error 	at sun.reflect.GeneratedMethodAccessor1552.invoke(Unknown Source)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1459)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
| Error 	at de.andreasschmitt.export.exporter.AbstractExporter.export(AbstractExporter.groovy:16)
| Error 	at de.andreasschmitt.export.exporter.DefaultPDFExporter.export(DefaultPDFExporter.groovy)

**Comment by bartoleo** [comment]
I found a way to use IDENTITY_H as pdf.encoding 
You must specify a TTF font that supports it (I used Arial.ttf)
