### ISSUE TITLE
Plugin is not working with grails 3.3.x

### ISSUE THREAD

**Issue by mrbadaw** [gpc/export#27]
Plugin is not working with grails 3.3.x

**Comment by hasalassh** [comment]
We are getting following error with grails 3.2.13

`Download https://repo.grails.org/grails/core/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.pom
Download https://repo.grails.org/grails/core/org/gebish/geb-exceptions/0.12.2/geb-exceptions-0.12.2.pom
Download https://repo.grails.org/grails/core/org/gebish/geb-implicit-assertions/0.12.2/geb-implicit-assertions-0.12.2.pom
Download https://repo.grails.org/grails/core/net/minidev/json-smart/2.2.1/json-smart-2.2.1.pom
Download https://repo.grails.org/grails/core/net/minidev/accessors-smart/1.1/accessors-smart-1.1.pom
Download https://repo.grails.org/grails/core/net/minidev/minidev-parent/2.2/minidev-parent-2.2.pom
Download https://repo.grails.org/grails/core/org/ow2/asm/asm/5.0.3/asm-5.0.3.pom
Download https://repo.grails.org/grails/core/org/ow2/asm/asm-parent/5.0.3/asm-parent-5.0.3.pom
Download https://repo.grails.org/grails/core/org/ow2/ow2/1.3/ow2-1.3.pom
Download https://repo.grails.org/grails/core/org/objenesis/objenesis/2.1/objenesis-2.1.pom
Download https://repo.grails.org/grails/core/org/objenesis/objenesis-parent/2.1/objenesis-parent-2.1.pom
Download https://repo.grails.org/grails/core/org/grails/grails-plugin-testing/3.2.13/grails-plugin-testing-3.2.13.jar
Download https://repo.grails.org/grails/core/org/grails/plugins/geb/1.0.2/geb-1.0.2.jar
Download https://repo.grails.org/grails/core/cglib/cglib/2.2.2/cglib-2.2.2.jar
Download https://repo.grails.org/grails/core/org/grails/grails-test/3.2.13/grails-test-3.2.13.jar
Download https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-starter-test/1.4.6.RELEASE/spring-boot-starter-test-1.4.6.RELEASE.jar
Download https://repo.grails.org/grails/core/org/spockframework/spock-spring/1.0-groovy-2.4/spock-spring-1.0-groovy-2.4.jar
Download https://repo.grails.org/grails/core/org/spockframework/spock-core/1.0-groovy-2.4/spock-core-1.0-groovy-2.4.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-spock/0.12.2/geb-spock-0.12.2.jar
Download https://repo.grails.org/grails/core/org/seleniumhq/selenium/selenium-support/2.53.1/selenium-support-2.53.1.jar
Download https://repo.grails.org/grails/core/asm/asm/3.3.1/asm-3.3.1.jar
Download https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-test/1.4.6.RELEASE/spring-boot-test-1.4.6.RELEASE.jar
Download https://repo.grails.org/grails/core/org/codehaus/groovy/groovy-test/2.4.10/groovy-test-2.4.10.jar
Download https://repo.grails.org/grails/core/org/springframework/boot/spring-boot-test-autoconfigure/1.4.6.RELEASE/spring-boot-test-autoconfigure-1.4.6.RELEASE.jar
Download https://repo.grails.org/grails/core/com/jayway/jsonpath/json-path/2.2.0/json-path-2.2.0.jar
Download https://repo.grails.org/grails/core/org/assertj/assertj-core/2.5.0/assertj-core-2.5.0.jar
Download https://repo.grails.org/grails/core/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar
Download https://repo.grails.org/grails/core/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
Download https://repo.grails.org/grails/core/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar
Download https://repo.grails.org/grails/core/org/skyscreamer/jsonassert/1.3.0/jsonassert-1.3.0.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-core/0.12.2/geb-core-0.12.2.jar
Download https://repo.grails.org/grails/core/org/seleniumhq/selenium/selenium-remote-driver/2.53.1/selenium-remote-driver-2.53.1.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-waiting/0.12.2/geb-waiting-0.12.2.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-ast/0.12.2/geb-ast-0.12.2.jar
Download https://repo.grails.org/grails/core/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar
Download https://repo.grails.org/grails/core/org/seleniumhq/selenium/selenium-api/2.53.1/selenium-api-2.53.1.jar
Download https://repo.grails.org/grails/core/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Download https://repo.grails.org/grails/core/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-exceptions/0.12.2/geb-exceptions-0.12.2.jar
Download https://repo.grails.org/grails/core/org/gebish/geb-implicit-assertions/0.12.2/geb-implicit-assertions-0.12.2.jar
Download https://repo.grails.org/grails/core/net/minidev/json-smart/2.2.1/json-smart-2.2.1.jar
Download https://repo.grails.org/grails/core/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar
Download https://repo.grails.org/grails/core/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
Download https://repo.grails.org/grails/core/org/objenesis/objenesis/2.1/objenesis-2.1.jar
startup failed:
General error during class generation: Unable to configure class node for class grails.plugins.export.ExportService due to malformed parameterized types
java.lang.RuntimeException: Unable to configure class node for class grails.plugins.export.ExportService due to malformed parameterized types
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:399)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:280)
	at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:1009)
	at org.codehaus.groovy.ast.ClassNode.getUnresolvedSuperClass(ClassNode.java:1004)
	at org.codehaus.groovy.ast.ClassNode.getSuperClass(ClassNode.java:998)
	at org.codehaus.groovy.ast.ClassNode.isDerivedFrom(ClassNode.java:941)
	at org.codehaus.groovy.classgen.asm.InvocationWriter.castToNonPrimitiveIfNecessary(InvocationWriter.java:896)
	at org.codehaus.groovy.classgen.asm.OperandStack.doConvertAndCast(OperandStack.java:403)
	at org.codehaus.groovy.classgen.asm.OperandStack.doGroovyCast(OperandStack.java:340)
	at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.evaluateEqual(BinaryExpressionHelper.java:445)
	at org.codehaus.groovy.classgen.asm.BinaryExpressionHelper.eval(BinaryExpressionHelper.java:129)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitBinaryExpression(AsmClassGenerator.java:685)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:51)
	at org.codehaus.groovy.classgen.asm.StatementWriter.writeExpressionStatement(StatementWriter.java:621)
	at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeExpressionStatement(OptimizingStatementWriter.java:411)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitExpressionStatement(AsmClassGenerator.java:667)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.classgen.asm.StatementWriter.writeBlockStatement(StatementWriter.java:93)
	at org.codehaus.groovy.classgen.asm.OptimizingStatementWriter.writeBlockStatement(OptimizingStatementWriter.java:205)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitBlockStatement(AsmClassGenerator.java:613)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:104)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitStdMethod(AsmClassGenerator.java:477)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitConstructorOrMethod(AsmClassGenerator.java:413)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:126)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethod(AsmClassGenerator.java:554)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1081)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:53)
	at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:259)
	at org.codehaus.groovy.control.CompilationUnit$17.call(CompilationUnit.java:848)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1087)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:174)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
	at org.gradle.process.internal.daemon.WorkerDaemonServer.execute(WorkerDaemonServer.java:28)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:370)
	... 60 more`

**Comment by m4rc77** [comment]
Worked for us with Grails 3.3.9, but now the build is broken due to #29

**Comment by miq** [comment]
I cannot reproduce this. We are using version 2.0.0 with Grails 6.2.3 for years in production now. Also note, that there was a release for Grails 7 lately.

If you rely on the plugin for Grail 3.x and still experience problems, feel free to reopen the issue.
